apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanjanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name:  USER_NAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-url   

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: Nodeport
  selector:
    app: webApp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
